create table if not exists public.journals (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  image_url text,
  is_public boolean not null default false,
  published_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.journals enable row level security;

create policy "Anyone can read public journals"
  on public.journals for select
  using (is_public = true);

create policy "Authenticated admins can read all journals"
  on public.journals for select to authenticated
  using (true);

create policy "Authenticated admins can insert journals"
  on public.journals for insert to authenticated
  with check (true);

create policy "Authenticated admins can update journals"
  on public.journals for update to authenticated
  using (true) with check (true);

create policy "Authenticated admins can delete journals"
  on public.journals for delete to authenticated
  using (true);